#pragma once
        
#include "syati.h"
#include "ModuleData_GalaxyLevelEngine_Hooks.h"

/* === GALAXY LEVEL ENGINE ===
*  - Syati Function Hooks -
*
*  These are Automatically generated by GLEBuildTool.
*  DO NOT MODIFY THIS FILE!
*  If a mistake occured while generating this header, please let me know.
*  https://www.github.com/SuperHackio/GalaxyLevelEngine/issues
*
*  Generation Information:
    "Generated: August 2, 2025 11:59:49 AM",
    "Symbol Count: 11",
    "Hook Count: 1",
    "GLE Version: V3.5.0.0"
*/

extern const u8 __hk__GLE__IsGalaxyAllComplete;

namespace GLE_HOOK_NAMESPACE {
    bool GLE__IsGalaxyAllComplete(const char * pStageName) {
        
        for (s32 i = 1; i < cModuleGLE__IsGalaxyAllCompleteTableCount; i++)
        {
            if (!cModuleGLE__IsGalaxyAllCompleteTable[i](pStageName))
    return false;
        }
        return true;
    }
    kmCall(&__hk__GLE__IsGalaxyAllComplete, GLE__IsGalaxyAllComplete);
}

// ----------------------------------------------------------------------------------------------------------------

