#pragma once

#include "syati.h"

/* === GALAXY LEVEL ENGINE ===
*  - Syati Function Bindings -
*
*  These are Automatically generated by GLEBuildTool.
*  DO NOT MODIFY THIS FILE!
*  If a mistake occured while generating this header, please let me know.
*  https://www.github.com/SuperHackio/GalaxyLevelEngine/issues
*
*  Generation Information:
    "Generated: August 2, 2025 11:59:49 AM",
    "Symbol Count: 11",
    "Hook Count: 1",
    "GLE Version: V3.5.0.0"
*/

// Galaxy Level Engine
namespace GLE {
    /**
      * \brief Changes the playback speed of the currently playing song (both AST and BMS).
      *
      * \param speed The new playback speed. Default speed is 1.0f
      * \param time The number of frames it takes to change to the new speed
      *
      **/
    void setAudioSpeed(f32 speed, s32 time);
    /**
      * \brief Changes the current BGM State based on what it's currently set to
      *
      * \param state The state to switch to relative to the current state
      * \param time The number of frames it takes to switch states fully
      *
      **/
    void addStageBGMState(s32 state, u32 time);
    /**
      * \brief Sets the NPC's BranchFunc to be GLE's Global Branch Function
      *
      * \param pNpc The NPCActor to assign the function to
      *
      * \throw DSI Exception if pNpc is NULL
      **/
    void registerGlobalBranchFunc(NPCActor * pNpc);
    /**
      * \brief Sets the NPC's EventFunc to be GLE's Global Event Function
      *
      * \param pNpc The NPCActor to assign the function to
      *
      * \throw DSI Exception if pNpc is NULL
      **/
    void registerGlobalEventFunc(NPCActor * pNpc);
    /**
      * \brief Sets the NPC's AnimeFunc to be GLE's Global NPC Animtion Function (A)
      * \brief This allows animations to be played via MSBF in tandem with the Galaxy's ZoneInfo.arc/NPCAnimeFunc.bcsv
      *
      * \param pNpc The NPCActor to assign the function to
      *
      * \throw DSI Exception if pNpc is NULL
      **/
    void registerGlobalAnimeFunc(NPCActor * pNpc);
    /**
      * \brief Calls the following functions (In order):
      * \brief GLE::registerGlobalBranchFunc
      * \brief GLE::registerGlobalEventFunc
      * \brief GLE::registerGlobalAnimeFunc
      *
      * \param pNpc The NPCActor to use as the Parameter for the function calls.
      *
      * \throw DSI Exception if pNpc is NULL
      **/
    void registerAllGlobalFuncs(NPCActor * pNpc);
    /**
      * \brief Attempts to get the ChangeSceneListInfo of the zone belonging to the provided ID
      *
      * \param zoneId The ID of the zone to access.
      * 
      *  0 will always refer to the main galaxy zone. (IslandFleetGalaxy, for example)
      *
      * \return A pointer to the ChangeSceneListInfo. NULL if not found.
      *
      **/
    JMapInfo* getChangeSceneListInfoFromZone(s32 zoneId);
    /**
      * \brief Attempts to get the StageInfo of the zone belonging to the provided ID
      *
      * \param zoneId The ID of the zone to access.
      * 
      *  0 will always refer to the main galaxy zone. (IslandFleetGalaxy, for example)
      *
      * \return A pointer to the StageInfo. NULL if not found.
      *
      **/
    JMapInfo* getStageInfoFromZone(s32 zoneId);
    /**
      * \brief Attempts to get a BCSV with the provided name from the "List" folder of the zone belonging to the provided ID
      *
      * \param zoneId The ID of the zone to access.
      * 
      *  0 will always refer to the main galaxy zone. (IslandFleetGalaxy, for example)
      * \param pFilename The name of the file to get from the Zone's List folder
      *
      * \return A pointer to the BCSV. NULL if not found.
      *
      **/
    JMapInfo* getListCsvFromZone(s32 zoneId, const char * pFilename);
    /**
      * \brief Uses the provided BCSV to attempt a scene change. The input BCSV must follow GLE's BCSV Scene Changing protocol
      * \brief https://github.com/SuperHackio/GalaxyLevelEngine/wiki/Scene-Changing
      *
      * \param pJMapInfo Pointer to the BCSV to use for changing scenes
      * \param index The index of the BCSV row to use
      *
      **/
    void requestMoveStageFromJMapInfo(const JMapInfo * pJMapInfo, s32 index);
    /**
      * \brief Uses the provided information to attempt a manual scene change.
      *
      * \param pStageName The internal name of the stage you want to go to
      * \param destScenario The scenario to load
      * 
      *  -1 will activate the Scenario Select
      * \param pZoneName The internal name of the Zone you want to spawn in.
      * 
      *  Set to NULL to use the Main Galaxy zone (IslandFleetGalaxy, for example)
      * \param destMarioNo The spawn point to spawn at (relative to the Zone selected by pZoneName)
      * \param playerChange Allows changing between Mario & Luigi
      * 
      *  -1 = Do not change
      * 
      *   0 = Force Mario
      * 
      *   1 = Force Luigi
      * 
      *   2 = Swap brothers (Mario becomes Luigi, Luigi becomes Mario)
      *
      **/
    void requestMoveStage(const char * pStageName, s32 destScenario, const char * pZoneName, s32 destMarioNo, s32 playerChange);
}

