#pragma once

/* === GALAXY LEVEL ENGINE ===
*  - Syati Function Hook Codegen -
*
*  These are Automatically generated by GLEBuildTool.
*  DO NOT MODIFY THIS FILE!
*  If a mistake occured while generating this header, please let me know.
*  https://www.github.com/SuperHackio/GalaxyLevelEngine/issues
*
*  Generation Information:
    "Generated: August 2, 2025 11:59:49 AM",
    "Symbol Count: 11",
    "Hook Count: 1",
    "GLE Version: V3.5.0.0"
*/

#include "BlueCoinUtil.h"


typedef bool (*HookFuncGLE__IsGalaxyAllCompleteDef)(const char *);

const HookFuncGLE__IsGalaxyAllCompleteDef cModuleGLE__IsGalaxyAllCompleteTable[] = {
    NULL,
BlueCoinUtil::checkStageBlueCoinCompletion, //BlueCoinAllCheck

};
const s32 cModuleGLE__IsGalaxyAllCompleteTableCount = sizeof(cModuleGLE__IsGalaxyAllCompleteTable) / sizeof(HookFuncGLE__IsGalaxyAllCompleteDef);

